/**
 * NewDataDisplay Component
 *
 * Displays generated structured data sections (NEW mode)
 * Shows sections generated by generate_full_report.py
 * Allows user to SELECT which sections to use (post-generation selection)
 */

'use client';

import { useState, useEffect } from 'react';
import { Card, Badge, Button, Collapse, Form, Alert } from 'react-bootstrap';

interface SectionData {
  section_id: string;
  section_title: string;
  content: string;
}

interface NewDataDisplayProps {
  sections: SectionData[];
  stockId: string;
  selectedSectionIds?: string[];
  onSelectionChange?: (sectionIds: string[]) => void;
  showSelection?: boolean; // Whether to show checkboxes for selection
  showOnlySelected?: boolean; // Whether to filter and show only selected sections
}

export default function NewDataDisplay({
  sections,
  stockId,
  selectedSectionIds = [],
  onSelectionChange,
  showSelection = true,
  showOnlySelected = false // By default, show all sections for selection
}: NewDataDisplayProps) {
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({});
  const [viewMode, setViewMode] = useState<'all' | 'selected'>(showOnlySelected ? 'selected' : 'all');

  const toggleSection = (sectionId: string) => {
    setExpandedSections(prev => ({
      ...prev,
      [sectionId]: !prev[sectionId]
    }));
  };

  const toggleSectionSelection = (sectionId: string) => {
    if (!onSelectionChange) return;

    const isSelected = selectedSectionIds.includes(sectionId);
    const newSelection = isSelected
      ? selectedSectionIds.filter(id => id !== sectionId)
      : [...selectedSectionIds, sectionId];

    onSelectionChange(newSelection);
  };

  const selectAll = () => {
    if (!onSelectionChange) return;
    onSelectionChange(sections.map(s => s.section_id));
  };

  const clearAll = () => {
    if (!onSelectionChange) return;
    onSelectionChange([]);
  };

  const expandAll = () => {
    const allExpanded: Record<string, boolean> = {};
    sections.forEach(s => { allExpanded[s.section_id] = true; });
    setExpandedSections(allExpanded);
  };

  const collapseAll = () => {
    setExpandedSections({});
  };

  return (
    <div style={{
      background: '#ffffff',
      borderRadius: '8px',
      padding: '24px',
      boxShadow: '0 2px 4px rgba(0,0,0,0.08)',
      marginBottom: '24px'
    }}>
      {/* Header */}
      <div style={{ marginBottom: '20px', borderBottom: '2px solid #e7f1ff', paddingBottom: '16px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <h3 style={{ fontSize: '20px', fontWeight: 600, color: '#212529', margin: 0 }}>
              <i className="bi bi-file-earmark-text me-2" style={{ color: '#198754' }}></i>
              Generated Structured Data (NEW Mode)
            </h3>
            <div style={{ fontSize: '14px', color: '#6c757d', marginTop: '8px' }}>
              Stock ID: <Badge bg="success">{stockId}</Badge>
              <span style={{ margin: '0 8px' }}>|</span>
              Sections Generated: <Badge bg="success">{sections.length}</Badge>
              {showSelection && (
                <>
                  <span style={{ margin: '0 8px' }}>|</span>
                  Selected: <Badge bg="primary">{selectedSectionIds.length}</Badge>
                </>
              )}
            </div>
          </div>

          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', justifyContent: 'flex-end' }}>
            {showSelection && (
              <>
                <Button
                  variant={viewMode === 'all' ? 'primary' : 'outline-primary'}
                  size="sm"
                  onClick={() => setViewMode('all')}
                >
                  <i className="bi bi-list-ul me-1"></i>
                  All Sections
                </Button>
                <Button
                  variant={viewMode === 'selected' ? 'primary' : 'outline-primary'}
                  size="sm"
                  onClick={() => setViewMode('selected')}
                  disabled={selectedSectionIds.length === 0}
                >
                  <i className="bi bi-check-square me-1"></i>
                  Selected Only
                </Button>
                <div style={{ borderLeft: '1px solid #dee2e6', height: '30px', margin: '0 4px' }}></div>
                <Button
                  variant="outline-primary"
                  size="sm"
                  onClick={selectAll}
                >
                  <i className="bi bi-check-all me-1"></i>
                  Select All
                </Button>
                <Button
                  variant="outline-secondary"
                  size="sm"
                  onClick={clearAll}
                >
                  <i className="bi bi-x me-1"></i>
                  Clear All
                </Button>
                <div style={{ borderLeft: '1px solid #dee2e6', height: '30px', margin: '0 4px' }}></div>
              </>
            )}
            <Button
              variant="outline-secondary"
              size="sm"
              onClick={expandAll}
            >
              <i className="bi bi-arrows-expand me-1"></i>
              Expand All
            </Button>
            <Button
              variant="outline-secondary"
              size="sm"
              onClick={collapseAll}
            >
              <i className="bi bi-arrows-collapse me-1"></i>
              Collapse All
            </Button>
          </div>
        </div>
      </div>

      {/* Selection Info */}
      {showSelection && (
        <Alert variant="info" style={{ marginBottom: '16px' }}>
          <i className="bi bi-info-circle me-2"></i>
          <small>
            <strong>Select sections to use:</strong> Check the boxes below to choose which sections will be included in your prompts and final output.
            {selectedSectionIds.length === 0 && <span className="text-danger ms-2">Please select at least one section.</span>}
          </small>
        </Alert>
      )}

      {/* Sections */}
      {sections.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '48px', color: '#6c757d' }}>
          <i className="bi bi-inbox" style={{ fontSize: '48px', display: 'block', marginBottom: '16px' }}></i>
          <p>No sections generated</p>
        </div>
      ) : (
        <div>
          {/* Filter based on view mode */}
          {sections
            .filter(section => viewMode === 'selected' ? selectedSectionIds.includes(section.section_id) : true)
            .map((section) => {
              const isSelected = selectedSectionIds.includes(section.section_id);

              return (
                <Card
                  key={section.section_id}
                  className="mb-3"
                  style={{
                    border: isSelected ? '2px solid #0d6efd' : '1px solid #dee2e6',
                    background: isSelected ? '#f8f9ff' : '#ffffff'
                  }}
                >
                <Card.Header
                  style={{
                    background: isSelected ? '#e7f1ff' : '#f8f9fa',
                    fontWeight: 600,
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    padding: '12px 16px'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flex: 1 }}>
                    {showSelection && (
                      <Form.Check
                        type="checkbox"
                        checked={isSelected}
                        onChange={() => toggleSectionSelection(section.section_id)}
                        onClick={(e) => e.stopPropagation()}
                        style={{ marginRight: '8px' }}
                      />
                    )}
                    <div onClick={() => toggleSection(section.section_id)} style={{ cursor: 'pointer', flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                      <div>
                        <Badge bg={isSelected ? 'primary' : 'success'} className="me-2">
                          Section {section.section_id}
                        </Badge>
                        {section.section_title}
                      </div>
                      <i
                        className={`bi bi-chevron-${expandedSections[section.section_id] ? 'up' : 'down'}`}
                        style={{ fontSize: '14px', color: '#6c757d' }}
                      ></i>
                    </div>
                  </div>
                </Card.Header>

                <Collapse in={expandedSections[section.section_id]}>
                  <Card.Body style={{ background: '#ffffff' }}>
                    <pre style={{
                      whiteSpace: 'pre-wrap',
                      fontSize: '13px',
                      margin: 0,
                      fontFamily: 'Consolas, Monaco, monospace',
                      lineHeight: '1.6',
                      color: '#212529',
                      background: '#f8f9fa',
                      padding: '16px',
                      borderRadius: '4px',
                      border: '1px solid #e9ecef'
                    }}>
                      {section.content}
                    </pre>
                  </Card.Body>
                </Collapse>
              </Card>
            );
          })}
        </div>
      )}

      {/* Footer */}
      <div style={{
        marginTop: '16px',
        paddingTop: '16px',
        borderTop: '1px solid #dee2e6',
        fontSize: '12px',
        color: '#6c757d'
      }}>
        <i className="bi bi-info-circle me-2"></i>
        This data was generated by <strong>generate_full_report.py</strong> for stock ID <strong>{stockId}</strong>
        {showSelection && selectedSectionIds.length > 0 && (
          <span className="ms-3">
            | <i className="bi bi-check-circle-fill text-primary me-1"></i>
            <strong>{selectedSectionIds.length}</strong> section{selectedSectionIds.length !== 1 ? 's' : ''} selected
          </span>
        )}
      </div>
    </div>
  );
}
